### ISSUE TITLE
Invalid column name 'ImportDate'.

### ISSUE THREAD

**Issue by denglender** [kipp-bayarea/google_classroom#102]
Our morning sync errored today with the following:
```
2020/09/04 11:00:36 - Google Classroom - Running on platform : Windows Server 2012 R2
2020/09/04 11:00:36 - Google Classroom - Executing command : cmd.exe /C "C:\Users\SZ\AppData\Local\Temp\kettle_637ecd0b-eebf-11ea-bf57-dfabbe81a29eshell.bat"
2020/09/04 11:00:36 - Google Classroom - (stdout) 
2020/09/04 11:00:36 - Google Classroom - (stdout) c:\users\sz\google_classroom\google_classroom>pipenv run python c:\users\sz\google_classroom\google_classroom\main.py 
2020/09/04 11:00:37 - Google Classroom - ERROR (version 6.1.0.1-196, build 1 from 2016-04-07 12.08.49 by buildguy) : (stderr) Loading .env environment variables…
2020/09/04 11:00:46 - Google Classroom - (stdout) 2020-09-04 11:00:46AM Eastern Daylight Time | INFO: OrgUnits: Generating requests...
2020/09/04 11:00:46 - Google Classroom - (stdout) 2020-09-04 11:00:46AM Eastern Daylight Time | INFO: OrgUnits: 1 requests remaining. On page 0.
2020/09/04 11:00:48 - Google Classroom - (stdout) 2020-09-04 11:00:48AM Eastern Daylight Time | INFO: EndPoint.batch_pull_data completed in 5.26 seconds.
2020/09/04 11:01:05 - Google Classroom - (stdout) 2020-09-04 11:01:05AM Eastern Daylight Time | INFO: StudentUsage: Generating requests...
2020/09/04 11:01:05 - Google Classroom - (stdout) 2020-09-04 11:01:05AM Eastern Daylight Time | INFO: StudentUsage: 6 requests remaining.
2020/09/04 11:01:11 - Google Classroom - (stdout) 2020-09-04 11:01:11AM Eastern Daylight Time | ERROR: (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Invalid column name 'ImportDate'. (207) (SQLExecute); [42S22] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Statement(s) could not be prepared. (8180)")
2020/09/04 11:01:11 - Google Classroom - (stdout) [SQL: INSERT INTO custom.[GoogleClassroom_StudentUsage] ([Email], [AsOfDate], [LastUsedTime], [ImportDate]) VALUES (?, ?, ?, ?)]
[...]
2020/09/04 11:01:11 - Google Classroom - (stdout) (Background on this error at: http://sqlalche.me/e/f405)
2020/09/04 11:01:11 - Google Classroom - (stdout) Traceback (most recent call last):
2020/09/04 11:01:11 - Google Classroom - (stdout)   File "C:\Users\SZ\.virtualenvs\google_classroom-Q34DGSlj\lib\site-packages\sqlalchemy\engine\base.py", line 1228, in _execute_context
2020/09/04 11:01:11 - Google Classroom - (stdout)     cursor, statement, parameters, context
2020/09/04 11:01:11 - Google Classroom - (stdout)   File "C:\Users\SZ\.virtualenvs\google_classroom-Q34DGSlj\lib\site-packages\sqlalchemy\dialects\mssql\pyodbc.py", line 413, in do_executemany
2020/09/04 11:01:11 - Google Classroom - (stdout)     cursor, statement, parameters, context=context
2020/09/04 11:01:11 - Google Classroom - (stdout)   File "C:\Users\SZ\.virtualenvs\google_classroom-Q34DGSlj\lib\site-packages\sqlalchemy\engine\default.py", line 587, in do_executemany
2020/09/04 11:01:11 - Google Classroom - (stdout)     cursor.executemany(statement, parameters)
2020/09/04 11:01:11 - Google Classroom - (stdout) pyodbc.ProgrammingError: ('42S22', "[42S22] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Invalid column name 'ImportDate'. (207) (SQLExecute); [42S22] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Statement(s) could not be prepared. (8180)")
2020/09/04 11:01:11 - Google Classroom - (stdout) 
2020/09/04 11:01:11 - Google Classroom - (stdout) The above exception was the direct cause of the following exception:
2020/09/04 11:01:11 - Google Classroom - (stdout) 
2020/09/04 11:01:11 - Google Classroom - (stdout) Traceback (most recent call last):
2020/09/04 11:01:11 - Google Classroom - (stdout)   File "c:\users\sz\google_classroom\google_classroom\main.py", line 174, in <module>
2020/09/04 11:01:11 - Google Classroom - (stdout)     main(Config)
2020/09/04 11:01:11 - Google Classroom - (stdout)   File "c:\users\sz\google_classroom\google_classroom\main.py", line 69, in main
2020/09/04 11:01:11 - Google Classroom - (stdout)     pull_data(config, creds, sql)
2020/09/04 11:01:11 - Google Classroom - (stdout)   File "c:\users\sz\google_classroom\google_classroom\main.py", line 96, in pull_data
2020/09/04 11:01:11 - Google Classroom - (stdout)     usage.batch_pull_data(dates=date_range_string, overwrite=False)
2020/09/04 11:01:11 - Google Classroom - (stdout)   File "c:\users\sz\google_classroom\google_classroom\timer.py", line 22, in wrapper
2020/09/04 11:01:11 - Google Classroom - (stdout)     results = func(*args, **kwargs)
2020/09/04 11:01:11 - Google Classroom - (stdout)   File "c:\users\sz\google_classroom\google_classroom\endpoints\base.py", line 265, in batch_pull_data
2020/09/04 11:01:11 - Google Classroom - (stdout)     self._write_to_db(df)
2020/09/04 11:01:11 - Google Classroom - (stdout)   File "c:\users\sz\google_classroom\google_classroom\endpoints\base.py", line 97, in _write_to_db
2020/09/04 11:01:11 - Google Classroom - (stdout)     self.sql.insert_into(self.table_name, df, chunksize=10000)
2020/09/04 11:01:11 - Google Classroom - (stdout)   File "C:\Users\SZ\.virtualenvs\google_classroom-Q34DGSlj\lib\site-packages\sqlsorcery\__init__.py", line 210, in insert_into
2020/09/04 11:01:11 - Google Classroom - (stdout)     dtype=dtype,
2020/09/04 11:01:11 - Google Classroom - (stdout)   File "C:\Users\SZ\.virtualenvs\google_classroom-Q34DGSlj\lib\site-packages\pandas\core\generic.py", line 2663, in to_sql
2020/09/04 11:01:11 - Google Classroom - (stdout)     method=method,
2020/09/04 11:01:11 - Google Classroom - (stdout)   File "C:\Users\SZ\.virtualenvs\google_classroom-Q34DGSlj\lib\site-packages\pandas\io\sql.py", line 521, in to_sql
2020/09/04 11:01:11 - Google Classroom - (stdout)     method=method,
2020/09/04 11:01:11 - Google Classroom - (stdout)   File "C:\Users\SZ\.virtualenvs\google_classroom-Q34DGSlj\lib\site-packages\pandas\io\sql.py", line 1317, in to_sql
2020/09/04 11:01:11 - Google Classroom - (stdout)     table.insert(chunksize, method=method)
2020/09/04 11:01:11 - Google Classroom - (stdout)   File "C:\Users\SZ\.virtualenvs\google_classroom-Q34DGSlj\lib\site-packages\pandas\io\sql.py", line 755, in insert
2020/09/04 11:01:11 - Google Classroom - (stdout)     exec_insert(conn, keys, chunk_iter)
2020/09/04 11:01:11 - Google Classroom - (stdout)   File "C:\Users\SZ\.virtualenvs\google_classroom-Q34DGSlj\lib\site-packages\pandas\io\sql.py", line 669, in _execute_insert
2020/09/04 11:01:11 - Google Classroom - (stdout)     conn.execute(self.table.insert(), data)
2020/09/04 11:01:11 - Google Classroom - (stdout)   File "C:\Users\SZ\.virtualenvs\google_classroom-Q34DGSlj\lib\site-packages\sqlalchemy\engine\base.py", line 984, in execute
2020/09/04 11:01:11 - Google Classroom - (stdout)     return meth(self, multiparams, params)
2020/09/04 11:01:11 - Google Classroom - (stdout)   File "C:\Users\SZ\.virtualenvs\google_classroom-Q34DGSlj\lib\site-packages\sqlalchemy\sql\elements.py", line 293, in _execute_on_connection
2020/09/04 11:01:11 - Google Classroom - (stdout)     return connection._execute_clauseelement(self, multiparams, params)
2020/09/04 11:01:11 - Google Classroom - (stdout)   File "C:\Users\SZ\.virtualenvs\google_classroom-Q34DGSlj\lib\site-packages\sqlalchemy\engine\base.py", line 1103, in _execute_clauseelement
2020/09/04 11:01:11 - Google Classroom - (stdout)     distilled_params,
2020/09/04 11:01:11 - Google Classroom - (stdout)   File "C:\Users\SZ\.virtualenvs\google_classroom-Q34DGSlj\lib\site-packages\sqlalchemy\engine\base.py", line 1288, in _execute_context
2020/09/04 11:01:11 - Google Classroom - (stdout)     e, statement, parameters, cursor, context
2020/09/04 11:01:11 - Google Classroom - (stdout)   File "C:\Users\SZ\.virtualenvs\google_classroom-Q34DGSlj\lib\site-packages\sqlalchemy\engine\base.py", line 1482, in _handle_dbapi_exception
2020/09/04 11:01:11 - Google Classroom - (stdout)     sqlalchemy_exception, with_traceback=exc_info[2], from_=e
2020/09/04 11:01:11 - Google Classroom - (stdout)   File "C:\Users\SZ\.virtualenvs\google_classroom-Q34DGSlj\lib\site-packages\sqlalchemy\util\compat.py", line 178, in raise_
2020/09/04 11:01:11 - Google Classroom - (stdout)     raise exception
2020/09/04 11:01:11 - Google Classroom - (stdout)   File "C:\Users\SZ\.virtualenvs\google_classroom-Q34DGSlj\lib\site-packages\sqlalchemy\engine\base.py", line 1228, in _execute_context
2020/09/04 11:01:11 - Google Classroom - (stdout)     cursor, statement, parameters, context
2020/09/04 11:01:11 - Google Classroom - (stdout)   File "C:\Users\SZ\.virtualenvs\google_classroom-Q34DGSlj\lib\site-packages\sqlalchemy\dialects\mssql\pyodbc.py", line 413, in do_executemany
2020/09/04 11:01:11 - Google Classroom - (stdout)     cursor, statement, parameters, context=context
2020/09/04 11:01:11 - Google Classroom - (stdout)   File "C:\Users\SZ\.virtualenvs\google_classroom-Q34DGSlj\lib\site-packages\sqlalchemy\engine\default.py", line 587, in do_executemany
2020/09/04 11:01:11 - Google Classroom - (stdout)     cursor.executemany(statement, parameters)
2020/09/04 11:01:11 - Google Classroom - (stdout) sqlalchemy.exc.ProgrammingError: (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Invalid column name 'ImportDate'. (207) (SQLExecute); [42S22] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Statement(s) could not be prepared. (8180)")
2020/09/04 11:01:11 - Google Classroom - (stdout) [SQL: INSERT INTO custom.[GoogleClassroom_StudentUsage] ([Email], [AsOfDate], [LastUsedTime], [ImportDate]) VALUES (?, ?, ?, ?)]
[...]
2020/09/04 11:01:11 - Google Classroom - (stdout) (Background on this error at: http://sqlalche.me/e/f405)
```

A couple days ago I pulled down the last few months of commits (in an attempt to see if that would address the deadlocking crash that we started to see again), so I'm guessing that's the proximal cause.  I can easily create what appears to be the missing column in our DB, just passing along as an FYI that there may have been a breaking change in the DB structure at some point.

**Comment by dchess** [comment]
@denglender Did your StudentUsage table not have the ImportDate column? I find that strange since the structure of this table has been those 4 columns since very early in the code development (as early as Mar 25 from what I see in the git history). @zkagin Are you aware of any breaking changes to the schema of that table at some point? Did it get removed and then added back at some point that you know of?

**Comment by denglender** [comment]
That's correct.

<img width="426" alt="stusage" src="https://user-images.githubusercontent.com/17971792/92257480-48ff6b00-eea3-11ea-9cb5-b64f5624d538.png">

**Comment by zkagin** [comment]
Thanks for reporting @denglender. It was added in #74, right after your commit adding Meet data, which might've been the last time you pulled.

@dchess Prior to that, the ImportDate was processed, but not being committed to the DB. #74 added it to the `columns` property so that it'd add the column as well.

Right now we don't handle any database migration, but now that the library is more complete we probably need to do so if we add more columns. I'm resolving this issue as I don't think we need to handle this particular instance given the limited number of people using the library before May.
