### ISSUE TITLE
SQL Deadlock

### ISSUE THREAD

**Issue by dchess** [kipp-bayarea/google_classroom#54]
When running the StudentSubmissions endpoint query, the following error occurs (and is only visible after retries are exhausted or disabled):

> sqlalchemy.exc.DBAPIError: (pyodbc.Error) ('40001', '[40001] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Transaction (Process ID 85) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction. (1205) (SQLExecDirectW)')
> [SQL: SELECT [INFORMATION_SCHEMA].[TABLES].[TABLE_NAME] 
> FROM [INFORMATION_SCHEMA].[TABLES] 
> WHERE [INFORMATION_SCHEMA].[TABLES].[TABLE_SCHEMA] = CAST(? AS NVARCHAR(max)) AND [INFORMATION_SCHEMA].[TABLES].[TABLE_TYPE] = CAST(? AS NVARCHAR(max)) ORDER BY [INFORMATION_SCHEMA].[TABLES].[TABLE_NAME]]
> [parameters: ('custom', 'BASE TABLE')]
> (Background on this error at: http://sqlalche.me/e/dbapi)

**Comment by zkagin** [comment]
Where is it catching? Perhaps one of the callbacks from the batch request is still writing to the DB at the same time as another callback is coming in. I would've thought in that case that Sqlalchemy handles the DB locking well, but perhaps we need to do some of it manually.

**Comment by dchess** [comment]
@zkagin It's unclear what's causing it but it's between batches. It's intermittent and subsequent reruns don't always produce the error, so you're thought about the callback may be right.

**Comment by dchess** [comment]
Closing this issue for now until we see it again.

**Comment by denglender** [comment]
Received this error intermittently as well.  Here's the one example I've seen thus far.  It was successful upon re-running the sript.

```
2020-05-10 10:11:23PM Eastern Daylight Time | INFO: Meet: 1 requests remaining.
On page 4.
2020-05-10 10:11:27PM Eastern Daylight Time | INFO: Meet: 1 requests remaining.
On page 5.
2020-05-10 10:11:32PM Eastern Daylight Time | ERROR: (pyodbc.Error) ('40001', '[
40001] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Transaction (Proces
s ID 108) was deadlocked on lock resources with another process and has been cho
sen as the deadlock victim. Rerun the transaction. (1205) (SQLExecDirectW)')
[SQL: SELECT [INFORMATION_SCHEMA].[TABLES].[TABLE_NAME]
FROM [INFORMATION_SCHEMA].[TABLES]
WHERE [INFORMATION_SCHEMA].[TABLES].[TABLE_SCHEMA] = CAST(? AS NVARCHAR(max)) AN
D [INFORMATION_SCHEMA].[TABLES].[TABLE_TYPE] = CAST(? AS NVARCHAR(max)) ORDER BY
 [INFORMATION_SCHEMA].[TABLES].[TABLE_NAME]]
[parameters: ('custom', 'BASE TABLE')]
(Background on this error at: http://sqlalche.me/e/dbapi)
Traceback (most recent call last):
  File "C:\Users\SZ\.virtualenvs\google_classroom-Q34DGSlj\lib\site-packages\sql
alchemy\engine\base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "C:\Users\SZ\.virtualenvs\google_classroom-Q34DGSlj\lib\site-packages\sql
alchemy\engine\default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
pyodbc.Error: ('40001', '[40001] [Microsoft][ODBC Driver 13 for SQL Server][SQL
Server]Transaction (Process ID 108) was deadlocked on lock resources with anothe
r process and has been chosen as the deadlock victim. Rerun the transaction. (12
05) (SQLExecDirectW)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 172, in <module>
    main(Config)
  File "main.py", line 167, in main
    Meet(admin_reports_service, sql, config).batch_pull_data()
  File "C:\Users\SZ\google_classroom\timer.py", line 22, in wrapper
    results = func(*args, **kwargs)
  File "C:\Users\SZ\google_classroom\api.py", line 239, in batch_pull_data
    self._write_to_db(df)
  File "C:\Users\SZ\google_classroom\api.py", line 80, in _write_to_db
    self.sql.insert_into(self.table_name, df, chunksize=10000)
  File "C:\Users\SZ\.virtualenvs\google_classroom-Q34DGSlj\lib\site-packages\sql
sorcery\__init__.py", line 210, in insert_into
    dtype=dtype,
  File "C:\Users\SZ\.virtualenvs\google_classroom-Q34DGSlj\lib\site-packages\pan
das\core\generic.py", line 2663, in to_sql
    method=method,
  File "C:\Users\SZ\.virtualenvs\google_classroom-Q34DGSlj\lib\site-packages\pan
das\io\sql.py", line 521, in to_sql
    method=method,
  File "C:\Users\SZ\.virtualenvs\google_classroom-Q34DGSlj\lib\site-packages\pan
das\io\sql.py", line 1324, in to_sql
    schema=schema or self.meta.schema, connection=conn
  File "C:\Users\SZ\.virtualenvs\google_classroom-Q34DGSlj\lib\site-packages\sql
alchemy\engine\base.py", line 2266, in table_names
    return self.dialect.get_table_names(conn, schema)
  File "<string>", line 2, in get_table_names
  File "C:\Users\SZ\.virtualenvs\google_classroom-Q34DGSlj\lib\site-packages\sql
alchemy\engine\reflection.py", line 44, in cache
    return fn(self, con, *args, **kw)
  File "C:\Users\SZ\.virtualenvs\google_classroom-Q34DGSlj\lib\site-packages\sql
alchemy\dialects\mssql\base.py", line 2166, in wrap
    **kw
  File "C:\Users\SZ\.virtualenvs\google_classroom-Q34DGSlj\lib\site-packages\sql
alchemy\dialects\mssql\base.py", line 2200, in _switch_db
    return fn(*arg, **kw)
  File "C:\Users\SZ\.virtualenvs\google_classroom-Q34DGSlj\lib\site-packages\sql
alchemy\dialects\mssql\base.py", line 2472, in get_table_names
    table_names = [r[0] for r in connection.execute(s)]
  File "C:\Users\SZ\.virtualenvs\google_classroom-Q34DGSlj\lib\site-packages\sql
alchemy\engine\base.py", line 984, in execute
    return meth(self, multiparams, params)
  File "C:\Users\SZ\.virtualenvs\google_classroom-Q34DGSlj\lib\site-packages\sql
alchemy\sql\elements.py", line 293, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\Users\SZ\.virtualenvs\google_classroom-Q34DGSlj\lib\site-packages\sql
alchemy\engine\base.py", line 1103, in _execute_clauseelement
    distilled_params,
  File "C:\Users\SZ\.virtualenvs\google_classroom-Q34DGSlj\lib\site-packages\sql
alchemy\engine\base.py", line 1288, in _execute_context
    cursor, statement, parameters, context
  File "C:\Users\SZ\.virtualenvs\google_classroom-Q34DGSlj\lib\site-packages\sql
alchemy\engine\default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DBAPIError: (pyodbc.Error) ('40001', '[40001] [Microsoft][ODBC Dr
iver 13 for SQL Server][SQL Server]Transaction (Process ID 108) was deadlocked o
n lock resources with another process and has been chosen as the deadlock victim
. Rerun the transaction. (1205) (SQLExecDirectW)')
[SQL: SELECT [INFORMATION_SCHEMA].[TABLES].[TABLE_NAME]
FROM [INFORMATION_SCHEMA].[TABLES]
WHERE [INFORMATION_SCHEMA].[TABLES].[TABLE_SCHEMA] = CAST(? AS NVARCHAR(max)) AN
D [INFORMATION_SCHEMA].[TABLES].[TABLE_TYPE] = CAST(? AS NVARCHAR(max)) ORDER BY
 [INFORMATION_SCHEMA].[TABLES].[TABLE_NAME]]
[parameters: ('custom', 'BASE TABLE')]
(Background on this error at: http://sqlalche.me/e/dbapi) 
```

**Comment by zkagin** [comment]
Thanks for reporting @denglender! By chance, were there any other services potentially reading from or writing to the DB at the time you were running the script?

@dchess I don't think there's any particular logic in our code here that would cause a deadlock, as we are batching the writes now and everything happens in sequence. If it is running into a deadlock with another service reading/writing at the same time, we could potentially add some retry logic, but I'd love to find a way to reproduce this error before we do. This may also be something we would rather solve in sqlsorcery, as ultimately the error here is in the single line:
```
self.sql.insert_into(self.table_name, df, chunksize=10000)
```
What do you think?

**Comment by denglender** [comment]
I can't imagine there would have been anything else writing to the database at that time.

It's possible, but still not likely, that something was reading from the database at that time.

**Comment by dchess** [comment]
@denglender Have you encountered this error again since you reported it?

**Comment by denglender** [comment]
I haven't noticed it, but to be honest, I also haven't been checking the error log (nor saving it), so I may not have noticed if it had happened.

**Comment by denglender** [comment]
Heads up - Did get this deadlock again today

```
2020/11/20 15:07:15 - Google Classroom - (stdout) 2020-11-20 03:07:15PM Eastern Standard Time | ERROR: (pyodbc.Error) ('40001', '[40001] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Transaction (Process ID 101) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction. (1205) (SQLExecDirectW)')
2020/11/20 15:07:15 - Google Classroom - (stdout) [SQL: SELECT [INFORMATION_SCHEMA].[TABLES].[TABLE_NAME] 
2020/11/20 15:07:15 - Google Classroom - (stdout) FROM [INFORMATION_SCHEMA].[TABLES] 
2020/11/20 15:07:15 - Google Classroom - (stdout) WHERE [INFORMATION_SCHEMA].[TABLES].[TABLE_SCHEMA] = CAST(? AS NVARCHAR(max)) AND [INFORMATION_SCHEMA].[TABLES].[TABLE_TYPE] = CAST(? AS NVARCHAR(max)) ORDER BY [INFORMATION_SCHEMA].[TABLES].[TABLE_NAME]]
2020/11/20 15:07:15 - Google Classroom - (stdout) [parameters: ('custom', 'BASE TABLE')]
2020/11/20 15:07:15 - Google Classroom - (stdout) (Background on this error at: http://sqlalche.me/e/dbapi)
2020/11/20 15:07:15 - Google Classroom - (stdout) Traceback (most recent call last):
2020/11/20 15:07:15 - Google Classroom - (stdout)   File "C:\Users\SZ\.virtualenvs\google_classroom-Q34DGSlj\lib\site-packages\sqlalchemy\engine\base.py", line 1248, in _execute_context
2020/11/20 15:07:15 - Google Classroom - (stdout)     cursor, statement, parameters, context
2020/11/20 15:07:15 - Google Classroom - (stdout)   File "C:\Users\SZ\.virtualenvs\google_classroom-Q34DGSlj\lib\site-packages\sqlalchemy\engine\default.py", line 590, in do_execute
2020/11/20 15:07:15 - Google Classroom - (stdout)     cursor.execute(statement, parameters)
2020/11/20 15:07:15 - Google Classroom - (stdout) pyodbc.Error: ('40001', '[40001] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Transaction (Process ID 101) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction. (1205) (SQLExecDirectW)')
2020/11/20 15:07:15 - Google Classroom - (stdout) 
2020/11/20 15:07:15 - Google Classroom - (stdout) The above exception was the direct cause of the following exception:
2020/11/20 15:07:15 - Google Classroom - (stdout) 
2020/11/20 15:07:15 - Google Classroom - (stdout) Traceback (most recent call last):
2020/11/20 15:07:15 - Google Classroom - (stdout)   File "c:\users\sz\google_classroom\google_classroom\main.py", line 174, in <module>
2020/11/20 15:07:15 - Google Classroom - (stdout)     main(Config)
2020/11/20 15:07:15 - Google Classroom - (stdout)   File "c:\users\sz\google_classroom\google_classroom\main.py", line 69, in main
2020/11/20 15:07:15 - Google Classroom - (stdout)     pull_data(config, creds, sql)
2020/11/20 15:07:15 - Google Classroom - (stdout)   File "c:\users\sz\google_classroom\google_classroom\main.py", line 163, in pull_data
2020/11/20 15:07:15 - Google Classroom - (stdout)     Meet(admin_reports_service, sql, config).batch_pull_data()
2020/11/20 15:07:15 - Google Classroom - (stdout)   File "c:\users\sz\google_classroom\google_classroom\timer.py", line 22, in wrapper
2020/11/20 15:07:15 - Google Classroom - (stdout)     results = func(*args, **kwargs)
2020/11/20 15:07:15 - Google Classroom - (stdout)   File "c:\users\sz\google_classroom\google_classroom\endpoints\base.py", line 265, in batch_pull_data
2020/11/20 15:07:15 - Google Classroom - (stdout)     self._write_to_db(df)
2020/11/20 15:07:15 - Google Classroom - (stdout)   File "c:\users\sz\google_classroom\google_classroom\endpoints\base.py", line 97, in _write_to_db
2020/11/20 15:07:15 - Google Classroom - (stdout)     self.sql.insert_into(self.table_name, df, chunksize=10000)
2020/11/20 15:07:15 - Google Classroom - (stdout)   File "C:\Users\SZ\.virtualenvs\google_classroom-Q34DGSlj\lib\site-packages\sqlsorcery\__init__.py", line 210, in insert_into
2020/11/20 15:07:15 - Google Classroom - (stdout)     dtype=dtype,
2020/11/20 15:07:15 - Google Classroom - (stdout)   File "C:\Users\SZ\.virtualenvs\google_classroom-Q34DGSlj\lib\site-packages\pandas\core\generic.py", line 2663, in to_sql
2020/11/20 15:07:15 - Google Classroom - (stdout)     method=method,
2020/11/20 15:07:15 - Google Classroom - (stdout)   File "C:\Users\SZ\.virtualenvs\google_classroom-Q34DGSlj\lib\site-packages\pandas\io\sql.py", line 521, in to_sql
2020/11/20 15:07:15 - Google Classroom - (stdout)     method=method,
2020/11/20 15:07:15 - Google Classroom - (stdout)   File "C:\Users\SZ\.virtualenvs\google_classroom-Q34DGSlj\lib\site-packages\pandas\io\sql.py", line 1324, in to_sql
2020/11/20 15:07:15 - Google Classroom - (stdout)     schema=schema or self.meta.schema, connection=conn
2020/11/20 15:07:15 - Google Classroom - (stdout)   File "C:\Users\SZ\.virtualenvs\google_classroom-Q34DGSlj\lib\site-packages\sqlalchemy\engine\base.py", line 2266, in table_names
2020/11/20 15:07:15 - Google Classroom - (stdout)     return self.dialect.get_table_names(conn, schema)
2020/11/20 15:07:15 - Google Classroom - (stdout)   File "<string>", line 2, in get_table_names
2020/11/20 15:07:15 - Google Classroom - (stdout)   File "C:\Users\SZ\.virtualenvs\google_classroom-Q34DGSlj\lib\site-packages\sqlalchemy\engine\reflection.py", line 44, in cache
2020/11/20 15:07:15 - Google Classroom - (stdout)     return fn(self, con, *args, **kw)
2020/11/20 15:07:15 - Google Classroom - (stdout)   File "C:\Users\SZ\.virtualenvs\google_classroom-Q34DGSlj\lib\site-packages\sqlalchemy\dialects\mssql\base.py", line 2166, in wrap
2020/11/20 15:07:15 - Google Classroom - (stdout)     **kw
2020/11/20 15:07:15 - Google Classroom - (stdout)   File "C:\Users\SZ\.virtualenvs\google_classroom-Q34DGSlj\lib\site-packages\sqlalchemy\dialects\mssql\base.py", line 2200, in _switch_db
2020/11/20 15:07:15 - Google Classroom - (stdout)     return fn(*arg, **kw)
2020/11/20 15:07:15 - Google Classroom - (stdout)   File "C:\Users\SZ\.virtualenvs\google_classroom-Q34DGSlj\lib\site-packages\sqlalchemy\dialects\mssql\base.py", line 2472, in get_table_names
2020/11/20 15:07:15 - Google Classroom - (stdout)     table_names = [r[0] for r in connection.execute(s)]
2020/11/20 15:07:15 - Google Classroom - (stdout)   File "C:\Users\SZ\.virtualenvs\google_classroom-Q34DGSlj\lib\site-packages\sqlalchemy\engine\base.py", line 984, in execute
2020/11/20 15:07:15 - Google Classroom - (stdout)     return meth(self, multiparams, params)
2020/11/20 15:07:15 - Google Classroom - (stdout)   File "C:\Users\SZ\.virtualenvs\google_classroom-Q34DGSlj\lib\site-packages\sqlalchemy\sql\elements.py", line 293, in _execute_on_connection
2020/11/20 15:07:15 - Google Classroom - (stdout)     return connection._execute_clauseelement(self, multiparams, params)
2020/11/20 15:07:15 - Google Classroom - (stdout)   File "C:\Users\SZ\.virtualenvs\google_classroom-Q34DGSlj\lib\site-packages\sqlalchemy\engine\base.py", line 1103, in _execute_clauseelement
2020/11/20 15:07:15 - Google Classroom - (stdout)     distilled_params,
2020/11/20 15:07:15 - Google Classroom - (stdout)   File "C:\Users\SZ\.virtualenvs\google_classroom-Q34DGSlj\lib\site-packages\sqlalchemy\engine\base.py", line 1288, in _execute_context
2020/11/20 15:07:15 - Google Classroom - (stdout)     e, statement, parameters, cursor, context
2020/11/20 15:07:15 - Google Classroom - (stdout)   File "C:\Users\SZ\.virtualenvs\google_classroom-Q34DGSlj\lib\site-packages\sqlalchemy\engine\base.py", line 1482, in _handle_dbapi_exception
2020/11/20 15:07:15 - Google Classroom - (stdout)     sqlalchemy_exception, with_traceback=exc_info[2], from_=e
2020/11/20 15:07:15 - Google Classroom - (stdout)   File "C:\Users\SZ\.virtualenvs\google_classroom-Q34DGSlj\lib\site-packages\sqlalchemy\util\compat.py", line 178, in raise_
2020/11/20 15:07:15 - Google Classroom - (stdout)     raise exception
2020/11/20 15:07:15 - Google Classroom - (stdout)   File "C:\Users\SZ\.virtualenvs\google_classroom-Q34DGSlj\lib\site-packages\sqlalchemy\engine\base.py", line 1248, in _execute_context
2020/11/20 15:07:15 - Google Classroom - (stdout)     cursor, statement, parameters, context
2020/11/20 15:07:15 - Google Classroom - (stdout)   File "C:\Users\SZ\.virtualenvs\google_classroom-Q34DGSlj\lib\site-packages\sqlalchemy\engine\default.py", line 590, in do_execute
2020/11/20 15:07:15 - Google Classroom - (stdout)     cursor.execute(statement, parameters)
2020/11/20 15:07:15 - Google Classroom - (stdout) sqlalchemy.exc.DBAPIError: (pyodbc.Error) ('40001', '[40001] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Transaction (Process ID 101) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction. (1205) (SQLExecDirectW)')
2020/11/20 15:07:15 - Google Classroom - (stdout) [SQL: SELECT [INFORMATION_SCHEMA].[TABLES].[TABLE_NAME] 
2020/11/20 15:07:15 - Google Classroom - (stdout) FROM [INFORMATION_SCHEMA].[TABLES] 
2020/11/20 15:07:15 - Google Classroom - (stdout) WHERE [INFORMATION_SCHEMA].[TABLES].[TABLE_SCHEMA] = CAST(? AS NVARCHAR(max)) AND [INFORMATION_SCHEMA].[TABLES].[TABLE_TYPE] = CAST(? AS NVARCHAR(max)) ORDER BY [INFORMATION_SCHEMA].[TABLES].[TABLE_NAME]]
2020/11/20 15:07:15 - Google Classroom - (stdout) [parameters: ('custom', 'BASE TABLE')]
2020/11/20 15:07:15 - Google Classroom - (stdout) (Background on this error at: http://sqlalche.me/e/dbapi)
```
